# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "052270658964ba4248a5ad4219f90afd"
name = "STILARO-VTON"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "stilaro-vton"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

